### ISSUE TITLE
/locations   is returning data with un-escaped newline characters in json data

### ISSUE THREAD

**Issue by ktarbet** [USACE/cwms-data-api#477] opened 2023-12-14 17:51 UTC
# Steps to reproduce:

curl -X 'GET' \
  'https://cwms-data.usace.army.mil/cwms-data/locations?office=SPK' \
  -H 'accept: application/json'

## example with a newline:
```
{"identity":{"office":"SPK","name":"CA10113","alternate-names":["Success Lake"]},"label":{"public-name":"Schafer Dam/Success Lake","long-name":"Success Lake and Dam","description":"Located on Tule River, CA to provide storage for flood control, conservation and other purposes.  Consists of a dam and reservoir on the Tule River.
"
```
## example 2
```
{"public-name":"Gunnison River at Delta","long-name":"USGS 09144250 Gunnison River at Delta","description":"USGS 09144250 Gunnison River at Delta, CO 38.7530556 108.0777778

USGS 09114500 Gunnison River nr Gunnison, CO"},"geolocation":
```

## Workaround

```csharp
jsonData = jsonData.Replace("\r\n", "\\n").Replace("\r", "\\r");
```

**Comment by rma-rripken** [comment] 2023-12-14 19:03
The cause of this bug is that  CWMS_LOC_PACKAGE.call_RETRIEVE_LOCATIONS_F doesn't do the proper escaping.
Retrieve_Locations_F is still being called by CDA from getAll.   
When users request a single location CDA queries the AV_LOC view and does its own serialization (with proper escaping).

https://github.com/USACE/cwms-data-api/blob/af2f69792fb9f648fb944361aa5f1abb534b09c9/cwms-data-api/src/main/java/cwms/cda/data/dao/LocationsDaoImpl.java#L95C1-L116C6

Here is a getOne example showing the correct escaping.  
```
curl -X 'GET' \
  'https://cwms-data.usace.army.mil/cwms-data/locations/Success%20Lake?office=SPK&unit=EN' \
  -H 'accept: application/json;version=2'
```

Response:
```
{
  "office-id": "SPK",
  "name": "Success Lake",
  "latitude": 36.0611111,
  "longitude": -118.9216667,
  "active": true,
  "public-name": "Schafer Dam/Success Lake",
  "long-name": "Success Lake and Dam",
  "description": "Located on Tule River, CA to provide storage for flood control, conservation and other purposes.  Consists of a dam and reservoir on the Tule River.\r\n",
  "timezone-name": "PST8PDT",
  "location-type": "RESERVOIR",
  "location-kind": "PROJECT",
  "nation": "US",
  "state-initial": "CA",
  "county-name": "Tulare",
  "nearest-city": "Porterville",
  "horizontal-datum": "WGS84",
  "vertical-datum": "NGVD29",
  "elevation": 589.99,
  "map-label": "Success Lake",
  "bounding-office-id": "SPK"
}
```

Also curious:  The getOne end-point only accepts the newer formats ( JSONv2 or XMLv2) and the getAll end-point only takes the old formats.  

We probably need to add the v2 formats to the getAll end-point.  Probably want to add paging to Locations as well.

**Comment by MikeNeilson** [comment] 2023-12-14 19:14
I think that's because I focus on the catalog endpoint for that data. maybe a redirect?

**Comment by ktarbet** [comment] 2023-12-14 19:20
I tried other formats (csv, and json) and get errors, unless I just let it default for the format.
from the swagger docs -- I can't tell if I should enter '2' (for csv) or 'csv'

This gives an error
```
curl -X 'GET' \
  'https://cwms-data.usace.army.mil/cwms-data/locations?office=SPK&format=json' \
  -H 'accept: application/json'
```

```
{
  "message": "failed to process request",
  "incidentIdentifier": "5867183783595083007",
  "details": {}
}
```

**Comment by rma-rripken** [comment] 2024-04-15 18:37
Possible tasks:
- [x] Revise the doc so that its clear that users don't need to pass "2" for csv.  
- [x] Add v2 datatypes to getAll end-point
- [ ] Add paging to getAll

**Comment by krowvin** [comment] 2024-11-21 14:46
The [national/public CDA](https://cwms-data.usace.army.mil/cwms-data) is behind in versions at the moment and still has this error for anyone who runs into that. 

But I can confirm on RC 15 the *individual* request for a gage is fixed:
![image](https://github.com/user-attachments/assets/e106e0e9-c5cb-480c-acd4-16e9ab9546b5)
i.e. 
`https://wm.swt.ds.usace.army.mil:8243/swt-data/locations/WACO?office=SWT`


**However**

Testing on RC 15 If I try this endpoint (the getAll) mentioned above:
```bash
curl -X 'GET' \
  'REDACTED:8243/swt-data/locations?office=SWT' \
  -H 'accept: application/json;version=2'
```

And get this error in swagger:
```json
{
  "message": "failed to process request",
  "incidentIdentifier": "-6188950685354644087",
  "details": {}
}
```
However, if I open the catalina log I see this:
```
21-Nov-2024 14:39:29.493 SEVERE [https-openssl-nio-REDACTED-8243-exec-3653] cwms.cda.api.LocationController.getAll -557324611885373515: failed to process request
        java.time.DateTimeException: Invalid ID for region-based ZoneId, invalid format: Unknown or Not Applicable
                at java.time.ZoneRegion.checkName(ZoneRegion.java:151)
                at java.time.ZoneRegion.ofId(ZoneRegion.java:116)
                at java.time.ZoneId.of(ZoneId.java:411)
                at java.time.ZoneId.of(ZoneId.java:359)
                at cwms.cda.data.dao.LocationsDaoImpl.buildLocation(LocationsDaoImpl.java:147)
                at org.jooq.RecordMapper.apply(RecordMapper.java:87)
                at org.jooq.RecordMapper.apply(RecordMapper.java:72)
                at java.util.stream.Collectors.lambda$mapping$8(Collectors.java:355)
                at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
                at java.util.Iterator.forEachRemaining(Iterator.java:116)
                at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
                at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
                at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
                at org.jooq.impl.AbstractCursor.collect(AbstractCursor.java:78)
                at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:361)
                at org.jooq.impl.ResultQueryTrait.fetch(ResultQueryTrait.java:1465)
                at cwms.cda.data.dao.LocationsDaoImpl.getLocations(LocationsDaoImpl.java:125)
                at cwms.cda.api.LocationController.getAll(LocationController.java:198)
                at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
                at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
                at cwms.cda.security.GuestAccessManager.manage(GuestAccessManager.java:28)
                at cwms.cda.security.MultipleAccessManager.manage(MultipleAccessManager.java:41)
                at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
                at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
                at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
                at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
                at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
                at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
                at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
                at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
                at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
                at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
                at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
                at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
                at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
                at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
                at cwms.cda.ApiServlet.service(ApiServlet.java:884)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:331)
                at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:158)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:597)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
                at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:241)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
                at java.lang.Thread.run(Thread.java:750)
```

**Comment by MikeNeilson** [comment] 2024-11-21 15:00
Closing in favor of new issue #957.

While basically the same error, this is in a different area of code that *is* maintained and updated.

**Closed as completed by MikeNeilson** 2024-11-21 15:00 UTC
Labels: approved-W192HQ23F0232-task4, locations
